### ISSUE TITLE
injected pod has no volume and hostPid property

### ISSUE THREAD

**Issue by zhangjianweibj** [tumblr/k8s-sidecar-injector#25]
hello ,i run k8s-sidecar-injector use yamls in example directory .then i modify debug-pod.yaml file:
![image](https://user-images.githubusercontent.com/18585129/65733659-47a9b800-e102-11e9-91f1-25608c6f97db.png)

and sidercar configmap:
![image](https://user-images.githubusercontent.com/18585129/65733697-6a3bd100-e102-11e9-9fea-b7b5b02a4c78.png)

then describe pod：
![image](https://user-images.githubusercontent.com/18585129/65733734-8ccdea00-e102-11e9-8baa-326795c1b8cf.png)

no volumounts hostnetwork and hostPid property. why?

**Comment by zhangjianweibj** [comment]
modify sidecar-confimg.yaml  file,bu still no mounts 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-telegraf-basic
  namespace: monitoring
  labels:
    app: k8s-sidecar-injector
    track: prod
data:
  sidecar-telegraf-basic: |
    name: sidecar-telegraf-basic
    hostNetwork: true
    hostPID: true
    containers:
    - name: telegraf-basic
      image: registry.icp.com:5000/service/lma/mcp-telegraf:0.1   
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9126
      volumeMounts:
        - name: telegraf-basic-directory
          mountPath: /etc/telegraf
    volumes:
    - name: telegraf-basic-directory
      configMap:
        name: telegraf-basic-config
---
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-basic-config
  namespace: monitoring
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "15s"
      round_interval = false
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "2s"

![image](https://user-images.githubusercontent.com/18585129/65739560-44212b80-e118-11e9-8a5b-b7545048f8f0.png)

**Comment by zhangjianweibj** [comment]
'''
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-telegraf-basic
  namespace: monitoring
  labels:
    app: k8s-sidecar-injector
    track: prod
data:
  sidecar-telegraf-basic: |
    name: sidecar-telegraf-basic
    hostNetwork: true
    hostPID: true
    containers:
    - name: telegraf-basic
      image: registry.icp.com:5000/service/lma/mcp-telegraf:0.1   
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9126
      volumeMounts:
        - name: telegraf-basic-directory
          mountPath: /etc/telegraf
    volumes:
    - name: telegraf-basic-directory
      configMap:
        name: telegraf-basic-config
---
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-basic-config
  namespace: monitoring
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "15s"
      round_interval = false
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "2s"

'''

**Comment by zhangjianweibj** [comment]
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-telegraf-basic
  namespace: monitoring
  labels:
    app: k8s-sidecar-injector
    track: prod
data:
  sidecar-telegraf-basic: |
    name: sidecar-telegraf-basic
    hostNetwork: true
    hostPID: true
    containers:
    - name: telegraf-basic
      image: registry.icp.com:5000/service/lma/mcp-telegraf:0.1   
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9126
      volumeMounts:
        - name: telegraf-basic-directory
          mountPath: /etc/telegraf
    volumes:
    - name: telegraf-basic-directory
      configMap:
        name: telegraf-basic-config
---
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-basic-config
  namespace: monitoring
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "15s"
      round_interval = false
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "2s"

```
