### ISSUE TITLE
sidercar-configmap namesapces must equal with k8s-sidecar-injector-prod namespace

### ISSUE THREAD

**Issue by zhangjianweibj** [tumblr/k8s-sidecar-injector#27]
i run injector with help of deployment.md 
yaml files is in project example directory.every thing is ok,then i run a diferent instances.
pod yaml file:
```
apiVersion: v1
kind: Pod
metadata:
  name: debian-debug
  namespace: monitoring
  annotations:
    injector.tumblr.com/request: sidecar-telegraf-basic
spec:
  containers:
  - image: debian:jessie
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10; done"]
    imagePullPolicy: IfNotPresent
    name: debian-debug
    resources:
      requests:
        memory: "200M"
        cpu: "500m"
  restartPolicy: Never
```

sidecar config file:

![image](https://user-images.githubusercontent.com/18585129/65751230-b0158b00-e13c-11e9-979d-839fe869ccf2.png)

k8s-sidecar-injector logs show " requested injection sidecar-telegraf-basic was not in configuration".

![image](https://user-images.githubusercontent.com/18585129/65750824-dd156e00-e13b-11e9-9759-90aa5c0674cf.png)

then i modify sidecar config file.modify namespaces which is equal with k8s-sidecar-injector's namespace.
![image](https://user-images.githubusercontent.com/18585129/65751376-fb2f9e00-e13c-11e9-9c56-c8f40d6ff3de.png)

and it works.
![image](https://user-images.githubusercontent.com/18585129/65751422-24e8c500-e13d-11e9-9a22-6a0060bc7851.png)

why??in my opinion,the target pods which namespace is monitoring, k8s-sidecar-injector should use sidecar config which namespace is monitirng.not kube-system.
